VERSION 0.7
FROM alpine:3.17.2@sha256:ff6bdca1701f3a8a67e328815ff2346b0e4067d32ec36b7992c1fdc001dc8517
WORKDIR /quotes

artifact:
  COPY in.txt ./quotes.txt
  RUN echo Generated quotes:
  RUN cat quotes.txt
  SAVE ARTIFACT quotes.txt
