VERSION 0.7
FROM alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
WORKDIR /quotes

artifact:
  COPY in.txt ./quotes.txt
  RUN echo Generated quotes:
  RUN cat quotes.txt
  SAVE ARTIFACT quotes.txt
