VERSION 0.7
FROM alpine:3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
WORKDIR /quotes

artifact:
  COPY in.txt ./quotes.txt
  RUN echo Generated quotes:
  RUN cat quotes.txt
  SAVE ARTIFACT quotes.txt
