VERSION 0.7
FROM  rust:1.71@sha256:b988926d2f8728a8ade9c308c94365615ecffa1a2f6d4cc9309c06bdc8f207a9
WORKDIR /rust-server


deps:
  COPY Cargo.lock Cargo.toml Rocket.toml quotes.txt .
  RUN mkdir src
  RUN touch src/main.rs # adding main.rs stub so cargo fetch works to prepare the cache
  RUN cargo fetch 

test:
  FROM +deps
  RUN cargo test

build:
  FROM +deps
  COPY --dir src .
  RUN cargo build --bin quote_server
  SAVE ARTIFACT target/debug/quote_server quote_server

docker:
  ARG --required tag
  FROM debian:buster-slim@sha256:bb3dc79fddbca7e8903248ab916bb775c96ec61014b3d02b4f06043b604726dc
  COPY +build/quote_server quote_server
  # We also have to copy Rocket.toml so that Rocket binds to the correct address and port within the container.
  COPY Rocket.toml Rocket.toml
  COPY ../quote_generator+artifact/quotes.txt quotes.txt
  EXPOSE 8000
  ENTRYPOINT ["./quote_server"]
  SAVE IMAGE --push ezeev/earthly-rust-example:$tag
