VERSION 0.7
FROM python:3.11@sha256:70e8e937c1da72df1688e883a2108b0feff03381187fa78eca6d9b10df411320
WORKDIR /py 

deps:
  RUN pip install wheel 
  COPY requirements.txt ./ 
  RUN pip wheel -r requirements.txt --wheel-dir=wheels


build:
  FROM +deps 
  COPY src src 
  #COPY quotes.txt ./
  COPY ../quote_generator+artifact/quotes.txt quotes.txt
  SAVE ARTIFACT src /src 
  SAVE ARTIFACT wheels /wheels 
  SAVE ARTIFACT quotes.txt ./


test:
  COPY +build/src src 
  COPY +build/wheels wheels 
  COPY +build/quotes.txt quotes.txt
  COPY ../quote_generator+artifact/quotes.txt quotes.txt
  COPY requirements.txt ./
  RUN pip install --no-index --find-links=wheels -r requirements.txt 
  RUN python src/test_quotes.py 


docker:
  ARG --required tag
  COPY +build/src src 
  COPY +build/wheels wheels 
  # quotes.txt needs to go into src for gunicorn to pick it up
  COPY +build/quotes.txt src/quotes.txt
  COPY start.sh ./
  COPY requirements.txt ./
  RUN pip install --no-index --find-links=wheels -r requirements.txt 
  EXPOSE 8002
  ENTRYPOINT ["./start.sh" ]
  SAVE IMAGE --push ezeev/earthly-python-example:$tag

